/*
# Provinces 5-7 Seed Data

Adding destinations for Lumbini, Karnali, and Sudurpashchim provinces.
*/

-- ============================================
-- PROVINCE 5: LUMBINI - 20 Places
-- ============================================
INSERT INTO destinations (name, slug, category, region, description, image_url, rating, review_count, altitude_m, difficulty, best_months, featured) VALUES
('Rani Mahal Trail', 'rani-mahal-trail', 'Heritage', 'Lumbini Province', 'Historic palace by the Kali Gandaki river. "Queen''s Palace" with colonial architecture.', 'https://images.unsplash.com/photo-1544735716-392fe5a5c385?w=800&q=80', 4.6, 28, 480, 'Easy', ARRAY['Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar'], true),
('Resunga Hill', 'resunga-hill', 'Hiking', 'Lumbini Province', 'Temple-covered hill in Gulmi. Pilgrimage site with valley views and sacred groves.', 'https://images.unsplash.com/photo-1501785888041-af3ef2d57d8a?w=800&q=80', 4.4, 19, 1400, 'Moderate', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Madane Lek', 'madane-lek', 'Hiking', 'Lumbini Province', 'Alpine meadows in Gulmi. Summer pastures with wildflowers and mountain views.', 'https://images.unsplash.com/photo-1452421827683-b3a5bdb7c813?w=800&q=80', 4.3, 11, 1800, 'Moderate', ARRAY['Mar', 'Apr', 'May'], false),
('Bardia Buffer Forest', 'bardia-buffer-forest', 'Wildlife', 'Lumbini Province', 'Buffer zone trails of Bardia National Park. Excellent for birdwatching and deer spotting.', 'https://images.unsplash.com/photo-1506905925346-21bda18d6ff1?w=800&q=80', 4.5, 23, 250, 'Easy', ARRAY['Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar'], false),
('Jitgadhi Fort', 'jitgadhi-fort', 'Heritage', 'Lumbini Province', 'Historic fort from Anglo-Nepal war. Memorial to brave Gurkha resistance.', 'https://images.unsplash.com/photo-1570179534610-9c1d8e3bdde7?w=800&q=80', 4.2, 8, 95, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Supa Deurali Trail', 'supa-deurali-trail', 'Hiking', 'Lumbini Province', 'Scenic highway-side hiking trail. Waterfall views and temperate forests.', 'https://images.unsplash.com/photo-1448375240586-882707db8882?w=800&q=80', 4.1, 6, 1100, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Jagdishpur Lake', 'jagdishpur-lake', 'Lake', 'Lumbini Province', 'Ramsar wetland site in Kapilvastu. 100+ bird species including rare migrants.', 'https://images.unsplash.com/photo-1439066615861-d1e4672a254d?w=800&q=80', 4.4, 17, 200, 'Easy', ARRAY['Nov', 'Dec', 'Jan', 'Feb'], false),
('Kabilas Forest', 'kabilas-forest', 'Hiking', 'Lumbini Province', 'Quiet forest reserve near Tansen. Sal and pine woods with hiking trails.', 'https://images.unsplash.com/photo-1448375240586-882707db8882?w=800&q=80', 4.0, 5, 1300, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Arghakhanchi Hills', 'arghakhanchi-hills', 'Hiking', 'Lumbini Province', 'Rolwaling-style hills with sunrise viewpoints. Traditional Thakuri villages.', 'https://images.unsplash.com/photo-1501785888041-af3ef2d57d8a?w=800&q=80', 4.3, 9, 1650, 'Moderate', ARRAY['Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar'], false),
('Swargadwari', 'swargadwari', 'Pilgrimage', 'Lumbini Province', 'Sacred Hindu pilgrimage site in Pyuthan. Ashram and meditation retreats.', 'https://images.unsplash.com/photo-1527684651878-5a8972479188?w=800&q=80', 4.5, 34, 1600, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Sisne Lake', 'sisne-lake', 'Lake', 'Lumbini Province', 'Hidden alpine lake in Rolpa. Surrounding forests rich in wildlife.', 'https://images.unsplash.com/photo-1439066615861-d1e4672a254d?w=800&q=80', 4.2, 4, 3200, 'Hard', ARRAY['May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct'], false),
('Rolpa Jaljala', 'rolpa-jaljala', 'Trekking', 'Lumbini Province', 'Rhododendron-covered trekking area. "Jaljala" means water lake in local dialect.', 'https://images.unsplash.com/photo-1452421827683-b3a5bdb7c813?w=800&q=80', 4.4, 12, 3000, 'Moderate', ARRAY['Apr', 'May'], false),
('Kapilvastu Ruins', 'kapilvastu-ruins', 'Heritage', 'Lumbini Province', 'Ancient Shakya kingdom ruins where Buddha grew up. Archaeological museum on-site.', 'https://images.unsplash.com/photo-1570179534610-9c1d8e3bdde7?w=800&q=80', 4.6, 45, 150, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], true),
('Bansgadhi Forest', 'bansgadhi-forest', 'Wildlife', 'Lumbini Province', 'Community forest known for rare birds and butterfly varieties. Nature trails.', 'https://images.unsplash.com/photo-1444021465936-c6ca81d6b3c8?w=800&q=80', 4.2, 7, 200, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Community Homestays Lumbini', 'community-homestays-lumbini', 'Cultural', 'Lumbini Province', 'Network of rural homestays across province. Experience authentic Tharu and Magar culture.', 'https://images.unsplash.com/photo-1527684651878-5a8972479188?w=800&q=80', 4.5, 21, 350, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Sandhikharka Ridge', 'sandhikharka-ridge', 'Hiking', 'Lumbini Province', 'Hill town with panoramic views. Gateway to Arghakhanchi''s hidden valleys.', 'https://images.unsplash.com/photo-1501785888041-af3ef2d57d8a?w=800&q=80', 4.1, 5, 1400, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Bulm Lake', 'bulm-lake', 'Lake', 'Lumbini Province', 'Small hidden lake in Gulmi. Local fishing and picnic spot, off tourist trail.', 'https://images.unsplash.com/photo-1439066615861-d1e4672a254d?w=800&q=80', 4.0, 3, 900, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Pyuthan Viewpoint', 'pyuthan-viewpoint', 'Hiking', 'Lumbini Province', 'Scenic hilltop with views of Dhaulagiri range. Dawn views spectacular.', 'https://images.unsplash.com/photo-1501785888041-af3ef2d57d8a?w=800&q=80', 4.3, 6, 1700, 'Easy', ARRAY['Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr'], false),
('Tansen Side Trails', 'tansen-side-trails', 'Hiking', 'Lumbini Province', 'Historic hill town''s surrounding trails. Traditional bazaar and Ranighat palace views.', 'https://images.unsplash.com/photo-1448375240586-882707db8882?w=800&q=80', 4.4, 15, 1350, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Rukum Villages', 'rukum-villages', 'Cultural', 'Lumbini Province', 'Authentic Magar villages in rebel heartlands. Rich culture, homestays, and organic farms.', 'https://images.unsplash.com/photo-1527684651878-5a8972479188?w=800&q=80', 4.5, 11, 1800, 'Moderate', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false);

-- ============================================
-- PROVINCE 6: KARNALI - 20 Places
-- ============================================
INSERT INTO destinations (name, slug, category, region, description, image_url, rating, review_count, altitude_m, difficulty, best_months, featured) VALUES
('Rara Hidden Shore', 'rara-hidden-shore', 'Lake', 'Karnali Province', 'Secluded beach on Rara Lake. Camping spots away from main tourist area. Crystal clear water.', 'https://images.unsplash.com/photo-1439066615861-d1e4672a254d?w=800&q=80', 4.9, 56, 2990, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], true),
('Murma Top', 'murma-top', 'Hiking', 'Karnali Province', 'Best panoramic viewpoint of Rara Lake. Easy climb with stunning sunrise views.', 'https://images.unsplash.com/photo-1501785888041-af3ef2d57d8a?w=800&q=80', 4.7, 34, 3200, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], true),
('Bulbule Lake', 'bulbule-lake', 'Lake', 'Karnali Province', 'Small spring-fed lake near Jumla. Local name means "bubbles" from fresh springs.', 'https://images.unsplash.com/photo-1439066615861-d1e4672a254d?w=800&q=80', 4.3, 8, 2700, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Sinja Valley', 'sinja-valley', 'Heritage', 'Karnali Province', 'Ancient Khasa kingdom capital. Archaeological sites with temple ruins and palace foundations.', 'https://images.unsplash.com/photo-1570179534610-9c1d8e3bdde7?w=800&q=80', 4.6, 19, 2400, 'Easy', ARRAY['May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct'], false),
('Kakrebihar', 'kakrebihar', 'Heritage', 'Karnali Province', '9th-century Buddhist monastery ruins. Intricate stone carvings overlooking Sinja valley.', 'https://images.unsplash.com/photo-1544735716-392fe5a5c385?w=800&q=80', 4.5, 12, 2250, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Chankheli Trek', 'chankheli-trek', 'Trekking', 'Karnali Province', 'Remote wild mountain trek rarely visited. Alpine meadows and dramatic passes.', 'https://images.unsplash.com/photo-1464822759023-fed622ff2cfa?w=800&q=80', 4.7, 7, 4800, 'Hard', ARRAY['Oct', 'Nov'], true),
('Phoksundo East Trail', 'phoksundo-east-trail', 'Trekking', 'Karnali Province', 'Alternative route to Shey Phoksundo with fewer tourists. Ancient Bonpo villages.', 'https://images.unsplash.com/photo-1501785888041-af3ef2d57d8a?w=800&q=80', 4.8, 15, 4200, 'Hard', ARRAY['May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct'], true),
('Upper Dolpo Villages', 'upper-dolpo-villages', 'Trekking', 'Karnali Province', 'Tibetan Buddhist villages beyond the Himalaya. Ancient monasteries and salt trade routes.', 'https://images.unsplash.com/photo-1527684651878-5a8972479188?w=800&q=80', 4.9, 23, 4000, 'Hard', ARRAY['May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct'], true),
('Ghodaghodi Grasslands', 'ghodaghodi-grasslands', 'Wildlife', 'Karnali Province', 'High-altitude grasslands with blue sheep and snow leopard habitat.', 'https://images.unsplash.com/photo-1506905925346-21bda18d6ff1?w=800&q=80', 4.4, 5, 3800, 'Hard', ARRAY['May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct'], false),
('Tila River', 'tila-river', 'Nature', 'Karnali Province', 'Scenic river valley through Jumla. Traditional irrigation channels and apple orchards.', 'https://images.unsplash.com/photo-1529158867021-99f5fd9a9772?w=800&q=80', 4.3, 9, 2500, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Jaljala Pass', 'jaljala-pass', 'Trekking', 'Karnali Province', 'High alpine pass connecting Jumla to Dolpa. Pristine rhododendron forests.', 'https://images.unsplash.com/photo-1452421827683-b3a5bdb7c813?w=800&q=80', 4.6, 6, 4400, 'Hard', ARRAY['May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct'], false),
('Dho Tarap', 'dho-tarap', 'Cultural', 'Karnali Province', 'Remote village in high valley. Unique blend of Bon and Buddhist traditions.', 'https://images.unsplash.com/photo-1527684651878-5a8972479188?w=800&q=80', 4.8, 14, 4080, 'Moderate', ARRAY['May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct'], true),
('Mugu Village Trail', 'mugu-village-trail', 'Trekking', 'Karnali Province', 'Authentic Himali village experience. Off-the-grid homestays in remote Karnali.', 'https://images.unsplash.com/photo-1527684651878-5a8972479188?w=800&q=80', 4.5, 8, 3000, 'Hard', ARRAY['May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct'], false),
('Limi Valley', 'limi-valley', 'Trekking', 'Karnali Province', 'Remote trans-Himalayan valley. Ancient salt trade route to Tibet. Untouched culture.', 'https://images.unsplash.com/photo-1464822759023-fed622ff2cfa?w=800&q=80', 4.9, 11, 4500, 'Hard', ARRAY['Jun', 'Jul', 'Aug', 'Sep'], true),
('Humla Forest', 'humla-forest', 'Wildlife', 'Karnali Province', 'High-altitude forest with blue sheep, Himalayan tahr, and snow leopard signs.', 'https://images.unsplash.com/photo-1448375240586-882707db8882?w=800&q=80', 4.4, 4, 3500, 'Hard', ARRAY['May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct'], false),
('Chyandi Hill', 'chyandi-hill', 'Hiking', 'Karnali Province', 'Local hiking spot near Jumla. Views of surrounding apple orchards and valley.', 'https://images.unsplash.com/photo-1501785888041-af3ef2d57d8a?w=800&q=80', 4.1, 3, 2800, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Chharka Bhot', 'chharka-bhot', 'Cultural', 'Karnali Province', 'Remote Tibetan-border village. Ancient monastery and traditional caravan stops.', 'https://images.unsplash.com/photo-1527684651878-5a8972479188?w=800&q=80', 4.7, 5, 4350, 'Hard', ARRAY['Jun', 'Jul', 'Aug', 'Sep'], false),
('Kanjiroba Trail', 'kanjiroba-trail', 'Trekking', 'Karnali Province', 'Challenging trek around Kanjiroba Himal. Technical peaks and glacier views.', 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&q=80', 4.8, 4, 5200, 'Hard', ARRAY['Oct', 'Nov'], false),
('Talcha Gateway', 'talcha-gateway', 'Nature', 'Karnali Province', 'High-altitude gateway to Rara. Small airstrip town with panoramic mountain views.', 'https://images.unsplash.com/photo-1501785888041-af3ef2d57d8a?w=800&q=80', 4.2, 7, 2800, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Karnali Riverside', 'karnali-riverside', 'Nature', 'Karnali Province', 'Camping along Nepal''s longest river. Fishing and traditional raft experiences.', 'https://images.unsplash.com/photo-1529158867021-99f5fd9a9772?w=800&q=80', 4.5, 11, 2500, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false);