/*
# Comprehensive Destination Data - Batch 3

Adding complete data for Province 5, 6, 7 destinations
*/

-- Province 5 (Lumbini) - Rani Mahal
UPDATE destinations SET 
  elevation_m = 800,
  difficulty = 'Easy',
  duration_days = '1 Day',
  transport = 'Drive from Butwal or Tansen (2-3 hrs)',
  budget_min = 2500,
  budget_max = 4000,
  network = 'Good',
  best_season = 'Oct-Mar',
  safety_info = 'Easy heritage visit near river.',
  sunrise_spot = 'River viewpoint',
  sunset_spot = 'Palace terrace',
  photography_tips = 'Historic palace with river backdrop.',
  nearest_hospital = 'Butwal Hospital',
  nearest_hospital_km = 35,
  nearest_police = 'Palpa Police',
  nearest_police_km = 5,
  nearest_health_post = 'Local Health Post',
  nearest_health_post_km = 2,
  local_rescue = 'Local volunteers',
  local_foods = ARRAY['Palpali Dhaka', 'Local vegetables'],
  cultural_tips = 'Historic 1887 AD palace of General Khadka Shamsher.',
  wildlife = ARRAY['River birds', 'Hill flora'],
  festivals_nearby = 'Dashain',
  things_to_respect = 'No graffiti, maintain heritage',
  score_adventure = 1,
  score_crowd = 4,
  score_cleanliness = 4,
  score_photography = 4,
  score_family = 5,
  score_budget = 5,
  score_safety = 5
WHERE name LIKE '%Rani Mahal%';

UPDATE destinations SET 
  elevation_m = 2300,
  difficulty = 'Moderate',
  duration_days = '3-4 Days',
  transport = 'Drive from Sandhikharka to Gulmi',
  budget_min = 14000,
  budget_max = 22000,
  network = 'Limited',
  best_season = 'Oct-Nov, Mar-May',
  safety_info = 'Remote hill trek. Guide recommended.',
  sunrise_spot = 'Resunga Peak',
  sunset_spot = 'Hill ridge',
  photography_tips = 'Stunning sunrise views from peak.',
  nearest_hospital = 'Sandhikharka Hospital',
  nearest_hospital_km = 30,
  nearest_police = 'Resunga Police',
  nearest_police_km = 5,
  nearest_health_post = 'Resunga Health Post',
  nearest_health_post_km = 3,
  local_rescue = 'Local volunteers',
  local_foods = ARRAY['Dal Bhat', 'Dhido', 'Local yogurt'],
  cultural_tips = 'Magar culture predominant.',
  wildlife = ARRAY['Monkeys', 'Birds', 'Rhododendron'],
  festivals_nearby = 'Maghe Sankranti',
  things_to_respect = 'Support local villages',
  score_adventure = 4,
  score_crowd = 5,
  score_cleanliness = 3,
  score_photography = 4,
  score_family = 2,
  score_budget = 3,
  score_safety = 4
WHERE name LIKE '%Resunga%';

UPDATE destinations SET 
  elevation_m = 2700,
  difficulty = 'Moderate',
  duration_days = '3-4 Days',
  transport = 'Drive from Burtibang, then trek',
  budget_min = 16000,
  budget_max = 25000,
  network = 'None',
  best_season = 'Oct-Nov, Mar-May',
  safety_info = 'Remote area with changing weather.',
  sunrise_spot = 'Madane Hilltop',
  sunset_spot = 'Lake shore',
  photography_tips = 'Madane Lake reflections at dawn.',
  nearest_hospital = 'Pyuthan Hospital',
  nearest_hospital_km = 45,
  nearest_police = 'Local Police Post',
  nearest_police_km = 15,
  nearest_health_post = 'Local Health Post',
  nearest_health_post_km = 8,
  local_rescue = 'Local community rescue',
  local_foods = ARRAY['Dal Bhat', 'Local herbs tea', 'Nettle soup'],
  cultural_tips = 'Remote Magar settlements.',
  wildlife = ARRAY['Musk Deer', 'Hill birds', 'Wild flowers'],
  festivals_nearby = 'Buddha Jayanti',
  things_to_respect = 'No washing in sacred lake',
  score_adventure = 4,
  score_crowd = 5,
  score_cleanliness = 4,
  score_photography = 4,
  score_family = 2,
  score_budget = 3,
  score_safety = 3
WHERE name LIKE '%Madane%';

-- Province 6 (Karnali)
UPDATE destinations SET 
  elevation_m = 3300,
  difficulty = 'Challenging',
  duration_days = '7-9 Days',
  transport = 'Flight to Jumla or trek from Nepalgunj',
  budget_min = 35000,
  budget_max = 55000,
  network = 'None',
  best_season = 'May-Oct',
  safety_info = 'High altitude, remote. Limited infrastructure. Guide essential.',
  sunrise_spot = 'Sinja Valley viewpoint',
  sunset_spot = 'Valley camp',
  photography_tips = 'Historic Sinja Valley - origin of Nepali language.',
  nearest_hospital = 'Jumla Hospital',
  nearest_hospital_km = 45,
  nearest_police = 'Sinja Police',
  nearest_police_km = 5,
  nearest_health_post = 'Sinja Health Post',
  nearest_health_post_km = 2,
  local_rescue = 'Local rescue volunteers',
  local_foods = ARRAY['Dal Bhat', 'Millet bread', 'Yak dairy'],
  cultural_tips = 'Historic capital of Khas Kingdom.',
  wildlife = ARRAY['Blue Sheep', 'Musk Deer', 'Migratory birds'],
  festivals_nearby = 'Dashain',
  things_to_respect = 'Preserve archaeological sites',
  score_adventure = 5,
  score_crowd = 5,
  score_cleanliness = 4,
  score_photography = 4,
  score_family = 1,
  score_budget = 1,
  score_safety = 2
WHERE name LIKE '%Sinja%';

UPDATE destinations SET 
  elevation_m = 3600,
  difficulty = 'Challenging',
  duration_days = '6-8 Days',
  transport = 'Trek from Jumla via Chankheli',
  budget_min = 32000,
  budget_max = 48000,
  network = 'None',
  best_season = 'May-Oct',
  safety_info = 'Remote trans-Himalayan region. Guide mandatory.',
  sunrise_spot = 'Pass summit',
  sunset_spot = 'Valley camps',
  photography_tips = 'Trans-Himalayan landscape.',
  nearest_hospital = 'Jumla Hospital',
  nearest_hospital_km = 70,
  nearest_police = 'Jumla Police',
  nearest_police_km = 65,
  nearest_health_post = 'Remote Health Post',
  nearest_health_post_km = 30,
  local_rescue = 'HRA/Jumla Rescue',
  local_foods = ARRAY['Tsampa', 'Tongba', 'Dal Bhat'],
  cultural_tips = 'Strong Tibetan Buddhist influence.',
  wildlife = ARRAY['Snow Leopard', 'Blue Sheep', 'Yaks'],
  festivals_nearby = 'Losar',
  things_to_respect = 'Clockwise in meditation sites',
  score_adventure = 5,
  score_crowd = 5,
  score_cleanliness = 4,
  score_photography = 4,
  score_family = 1,
  score_budget = 1,
  score_safety = 2
WHERE name LIKE '%Limi%' OR name LIKE '%Upper Dolpo%';

UPDATE destinations SET 
  elevation_m = 4200,
  difficulty = 'Challenging',
  duration_days = '12-15 Days',
  transport = 'Flight to Juphal, then trek',
  budget_min = 55000,
  budget_max = 85000,
  network = 'None',
  best_season = 'May-Sep',
  safety_info = 'Extreme remote. Satellite phone recommended. Guide mandatory.',
  sunrise_spot = 'Shey camps',
  sunset_spot = 'Lake shore',
  photography_tips = 'Crystal mountain and sacred Shey monastery.',
  nearest_hospital = 'Dolpa Hospital',
  nearest_hospital_km = 80,
  nearest_police = 'Dunai Police',
  nearest_police_km = 60,
  nearest_health_post = 'Remote health posts',
  nearest_health_post_km = 25,
  local_rescue = 'HRA Rescue',
  local_foods = ARRAY['Tsampa', 'Yak butter tea', 'Dal Bhat'],
  cultural_tips = 'Buddhist monastic tradition.',
  wildlife = ARRAY['Snow Leopard', 'Blue Sheep', 'Musk Deer'],
  festivals_nearby = 'Losar',
  things_to_respect = 'Maintain silence near monastery, no meat in sacred areas',
  score_adventure = 5,
  score_crowd = 5,
  score_cleanliness = 4,
  score_photography = 5,
  score_family = 1,
  score_budget = 1,
  score_safety = 1
WHERE name LIKE '%Phoksundo%' OR name LIKE '%Shey%';

-- Province 7 (Sudurpashchim)
UPDATE destinations SET 
  elevation_m = 4143,
  difficulty = 'Challenging',
  duration_days = '8-10 Days',
  transport = 'Trek from Kolti or Talkot (flight from Dhangadi)',
  budget_min = 42000,
  budget_max = 65000,
  network = 'None',
  best_season = 'May-Oct',
  safety_info = 'Very remote. Limited rescue options. Guide mandatory.',
  sunrise_spot = 'Badimalika Summit',
  sunset_spot = 'Temple area',
  photography_tips = 'Sacred high altitude pilgrimage site.',
  nearest_hospital = 'Bayalpata Hospital',
  nearest_hospital_km = 50,
  nearest_police = 'Kolti Police',
  nearest_police_km = 20,
  nearest_health_post = 'Local health posts',
  nearest_health_post_km = 15,
  local_rescue = 'Local rescue volunteers',
  local_foods = ARRAY['Dal Bhat', 'Local herbs', 'Tongba'],
  cultural_tips = 'Sacred to Nepali Hindus - manifestation of goddess.',
  wildlife = ARRAY['Musk Deer', 'Himalayan Thar', 'Monal Pheasant'],
  festivals_nearby = 'Janai Purnima',
  things_to_respect = 'Pilgrimage site - pure veg, no alcohol',
  score_adventure = 5,
  score_crowd = 5,
  score_cleanliness = 3,
  score_photography = 4,
  score_family = 1,
  score_budget = 1,
  score_safety = 2
WHERE name LIKE '%Badimalika%';

UPDATE destinations SET 
  elevation_m = 3600,
  difficulty = 'Moderate',
  duration_days = '3-4 Days',
  transport = 'Trek from Chainpur (Baitadi)',
  budget_min = 18000,
  budget_max = 28000,
  network = 'None',
  best_season = 'Oct-Nov, Mar-May',
  safety_info = 'Remote hill and grassland. Changing weather.',
  sunrise_spot = 'Ramaroshan viewpoint',
  sunset_spot = 'Grassland area',
  photography_tips = 'Unique rolling grasslands and twelve lakes.',
  nearest_hospital = 'Baitadi Hospital',
  nearest_hospital_km = 40,
  nearest_police = 'Chainpur Police',
  nearest_police_km = 15,
  nearest_health_post = 'Local Health Post',
  nearest_health_post_km = 5,
  local_rescue = 'Local volunteers',
  local_foods = ARRAY['Dal Bhat', 'Local herbs tea', 'Dhido'],
  cultural_tips = 'Religious significance for Hindus.',
  wildlife = ARRAY['Deer', 'Wild fowl', 'Lake birds'],
  festivals_nearby = 'Gaura Parva',
  things_to_respect = 'No fishing in lakes',
  score_adventure = 4,
  score_crowd = 5,
  score_cleanliness = 4,
  score_photography = 4,
  score_family = 2,
  score_budget = 3,
  score_safety = 3
WHERE name LIKE '%Ramaroshan%';

UPDATE destinations SET 
  elevation_m = 7132,
  difficulty = 'Challenging',
  duration_days = '10-14 Days',
  transport = 'Trek from Ghusa or Sunikhet',
  budget_min = 50000,
  budget_max = 80000,
  network = 'None',
  best_season = 'May-Oct',
  safety_info = 'High altitude expedition trek. Technical expertise needed.',
  sunrise_spot = 'Base camp',
  sunset_spot = 'High camps',
  photography_tips = 'Stunning Api and Nampa peaks.',
  nearest_hospital = 'Darchula Hospital',
  nearest_hospital_km = 60,
  nearest_police = 'Darchula Police',
  nearest_police_km = 50,
  nearest_health_post = 'Remote health posts',
  nearest_health_post_km = 20,
  local_rescue = 'HRA Rescue Team',
  local_foods = ARRAY['Tsampa', 'Tongba', 'Dal Bhat'],
  cultural_tips = 'Strong mountain traditions.',
  wildlife = ARRAY['Snow Leopard', 'Blue Sheep', 'Himalayan Thar'],
  festivals_nearby = 'Dashain',
  things_to_respect = 'Technical climbing skills essential',
  score_adventure = 5,
  score_crowd = 5,
  score_cleanliness = 4,
  score_photography = 5,
  score_family = 1,
  score_budget = 1,
  score_safety = 1
WHERE name LIKE '%Api%' OR name LIKE '%Saipal%';

-- Update remaining destinations with sensible defaults based on difficulty
UPDATE destinations SET 
  local_foods = COALESCE(local_foods, ARRAY['Dal Bhat', 'Chiya', 'Local snacks']),
  wildlife = COALESCE(wildlife, ARRAY['Local birds', 'Hill flora']),
  festivals_nearby = COALESCE(festivals_nearby, 'Dashain, Tihar'),
  things_to_respect = COALESCE(things_to_respect, 'Respect local customs, dress modestly')
WHERE local_foods IS NULL;