/*
# Provinces 3-7 Seed Data

Adding destinations for Bagmati, Gandaki, Lumbini, Karnali, and Sudurpashchim provinces.
*/

-- ============================================
-- PROVINCE 3: BAGMATI - 20 Places
-- ============================================
INSERT INTO destinations (name, slug, category, region, description, image_url, rating, review_count, altitude_m, difficulty, best_months, featured) VALUES
('Ghyampe Danda', 'ghyampe-danda', 'Hiking', 'Bagmati Province', 'Hidden hilltop viewpoint near Chandragiri. Panoramic Kathmandu valley and Himalaya views.', 'https://images.unsplash.com/photo-1501785888041-af3ef2d57d8a?w=800&q=80', 4.5, 18, 2200, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], true),
('Bheda Kharka', 'bheda-kharka', 'Hiking', 'Bagmati Province', 'Alpine meadows above Nagarkot. Seasonal sheep grazing with stunning sunrise views.', 'https://images.unsplash.com/photo-1464822759023-fed622ff2cfa?w=800&q=80', 4.6, 14, 2450, 'Moderate', ARRAY['Mar', 'Apr', 'May', 'Sep', 'Oct', 'Nov'], true),
('Phulchoki East Trail', 'phulchoki-east-trail', 'Hiking', 'Bagmati Province', 'Less crowded route to Phulchoki peak. Dense rhododendron forest with 300+ bird species.', 'https://images.unsplash.com/photo-1452421827683-b3a5bdb7c813?w=800&q=80', 4.5, 22, 2780, 'Moderate', ARRAY['Mar', 'Apr', 'May'], false),
('Tarebhir', 'tarebhir', 'Hiking', 'Bagmati Province', 'Dramatic cliff viewpoint near Budhanilkantha. Popular for paragliding and photography.', 'https://images.unsplash.com/photo-1501785888041-af3ef2d57d8a?w=800&q=80', 4.3, 33, 1900, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Nagidanda', 'nagidanda', 'Hiking', 'Bagmati Province', 'Quiet hill station near Bhaktapur. Local weekend escape with valley panoramas.', 'https://images.unsplash.com/photo-1448375240586-882707db8882?w=800&q=80', 4.2, 11, 1850, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Chisapani Sundarijal', 'chisapani-sundarijal', 'Trekking', 'Bagmati Province', 'Classic trail through Shivapuri National Park. Forest walk to Chisapani ridge viewpoint.', 'https://images.unsplash.com/photo-1448375240586-882707db8882?w=800&q=80', 4.7, 56, 2150, 'Moderate', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], true),
('Panch Pokhari', 'panch-pokhari', 'Trekking', 'Bagmati Province', 'Five sacred lakes at 4100m. Janai Purnima pilgrimage site with pristine wilderness.', 'https://images.unsplash.com/photo-1439066615861-d1e4672a254d?w=800&q=80', 4.8, 28, 4100, 'Hard', ARRAY['May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct'], true),
('Taudaha', 'taudaha', 'Lake', 'Bagmati Province', 'Ancient lake on Kathmandu''s edge. Mythological site where the valley was drained. Bird sanctuary.', 'https://images.unsplash.com/photo-1439066615861-d1e4672a254d?w=800&q=80', 4.1, 45, 1350, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Daman Viewpoint', 'daman-viewpoint', 'Hiking', 'Bagmati Province', '360-degree Himalayan viewpoint on Tribhuvan Highway. Resort town with mountain panoramas.', 'https://images.unsplash.com/photo-1501785888041-af3ef2d57d8a?w=800&q=80', 4.6, 39, 2320, 'Easy', ARRAY['Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr'], false),
('Bethanchok', 'bethanchok', 'Hiking', 'Bagmati Province', 'Known as "King of Hills" near Kavre. Unobstructed views from Langtang to Everest.', 'https://images.unsplash.com/photo-1464822759023-fed622ff2cfa?w=800&q=80', 4.7, 17, 2450, 'Moderate', ARRAY['Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar'], true),
('Lakuri Bhanjyang', 'lakuri-bhanjyang', 'Hiking', 'Bagmati Province', 'Forest trail popular for mountain biking and hiking. Rhododendron and pine woods.', 'https://images.unsplash.com/photo-1448375240586-882707db8882?w=800&q=80', 4.4, 25, 2100, 'Moderate', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Panauti Heritage', 'panauti-heritage', 'Cultural', 'Bagmati Province', 'Medieval Newari town with 12th-century temples. Living museum of traditional architecture.', 'https://images.unsplash.com/photo-1544735716-392fe5a5c385?w=800&q=80', 4.6, 41, 1450, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Namo Buddha', 'namo-buddha', 'Cultural', 'Bagmati Province', 'Pilgrimage trail to sacred Buddhist stupa. Legend of Buddha offering his body to a tigress.', 'https://images.unsplash.com/photo-1527684651878-5a8972479188?w=800&q=80', 4.7, 67, 1750, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], true),
('Indrasarovar', 'indrasarovar', 'Lake', 'Bagmati Province', 'Nepal''s largest reservoir at Kulekhani. Boating and fishing with hill scenery.', 'https://images.unsplash.com/photo-1439066615861-d1e4672a254d?w=800&q=80', 4.3, 19, 1530, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Chitlang Village', 'chitlang-village', 'Cultural', 'Bagmati Province', 'Organic farming village in a hidden valley. Goat cheese, organic produce, village homestays.', 'https://images.unsplash.com/photo-1527684651878-5a8972479188?w=800&q=80', 4.5, 38, 1850, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Tistung', 'tistung', 'Nature', 'Bagmati Province', 'Terraced hills and organic farms on Tribhuvan Highway. Cool climate escape from Kathmandu.', 'https://images.unsplash.com/photo-1448375240586-882707db8882?w=800&q=80', 4.2, 12, 1950, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Markhu', 'markhu', 'Lake', 'Bagmati Province', 'Peaceful settlement on Kulekhani reservoir. Boating, fishing, and hill walks.', 'https://images.unsplash.com/photo-1439066615861-d1e4672a254d?w=800&q=80', 4.4, 16, 1500, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Kulekhani Forest', 'kulekhani-forest', 'Hiking', 'Bagmati Province', 'Quiet pine and rhododendron forest around the reservoir. Escape from city crowds.', 'https://images.unsplash.com/photo-1448375240586-882707db8882?w=800&q=80', 4.3, 8, 1800, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Bajrabarahi Forest', 'bajrabarahi-forest', 'Hiking', 'Bagmati Province', 'Sacred forest around the Bajrabarahi temple. Ancient trees and meditation spots.', 'https://images.unsplash.com/photo-1444021465936-c6ca81d6b3c8?w=800&q=80', 4.2, 13, 1550, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Ranikot', 'ranikot', 'Hiking', 'Bagmati Province', 'Remote hilltop offering spectacular sunrise over the Himalaya. Minimal tourist infrastructure.', 'https://images.unsplash.com/photo-1501785888041-af3ef2d57d8a?w=800&q=80', 4.5, 7, 2100, 'Moderate', ARRAY['Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr'], false);

-- ============================================
-- PROVINCE 4: GANDAKI - 20 Places
-- ============================================
INSERT INTO destinations (name, slug, category, region, description, image_url, rating, review_count, altitude_m, difficulty, best_months, featured) VALUES
('Mohare Danda', 'mohare-danda', 'Trekking', 'Gandaki Province', 'Community eco-trek with sustainable homestays. Perfect views of Dhaulagiri and Annapurna.', 'https://images.unsplash.com/photo-1464822759023-fed622ff2cfa?w=800&q=80', 4.8, 67, 3300, 'Moderate', ARRAY['Oct', 'Nov', 'Mar', 'Apr'], true),
('Khumai Danda', 'khumai-danda', 'Trekking', 'Gandaki Province', 'Hidden gem with dramatic Annapurna south face views. Part of community trek initiative.', 'https://images.unsplash.com/photo-1501785888041-af3ef2d57d8a?w=800&q=80', 4.9, 45, 3245, 'Moderate', ARRAY['Mar', 'Apr', 'Oct', 'Nov'], true),
('Kapuche Lake', 'kapuche-lake', 'Lake', 'Gandaki Province', 'World''s lowest altitude glacier lake at 2450m. Crystal clear waters reflecting Annapurna.', 'https://images.unsplash.com/photo-1439066615861-d1e4672a254d?w=800&q=80', 4.8, 33, 2450, 'Moderate', ARRAY['Mar', 'Apr', 'May'], true),
('Sikles Village', 'sikles-village', 'Cultural', 'Gandaki Province', 'Authentic Gurung village at 2000m. Traditional houses, cultural shows, and organic farms.', 'https://images.unsplash.com/photo-1527684651878-5a8972479188?w=800&q=80', 4.6, 28, 2000, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Narchyang', 'narchyang', 'Nature', 'Gandaki Province', 'Hidden waterfalls and hot springs near Beni. Gate to Dhaulagiri with minimal tourists.', 'https://images.unsplash.com/photo-1432405972618-c60b022228b2?w=800&q=80', 4.4, 12, 1700, 'Moderate', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Panchase Hill', 'panchase-hill', 'Hiking', 'Gandaki Province', 'Sacred hill with panoramic views. Dense rhododendron forests and pilgrimage sites.', 'https://images.unsplash.com/photo-1452421827683-b3a5bdb7c813?w=800&q=80', 4.5, 38, 2500, 'Moderate', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Khayar Lake', 'khayar-lake', 'Trekking', 'Gandaki Province', 'Sacred lake at 4500m in Annapurna sanctuary. Pristine glacial waters, full moon pilgrimage.', 'https://images.unsplash.com/photo-1439066615861-d1e4672a254d?w=800&q=80', 4.7, 15, 4500, 'Hard', ARRAY['May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct'], false),
('Dudhpokhari', 'dudhpokhari', 'Lake', 'Gandaki Province', 'Alpine lake near Gorkha. "Milk Lake" named for its white color. Remote and pristine.', 'https://images.unsplash.com/photo-1439066615861-d1e4672a254d?w=800&q=80', 4.5, 9, 3800, 'Hard', ARRAY['May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov'], false),
('Rupa Lake', 'rupa-lake', 'Lake', 'Gandaki Province', 'Peaceful twin lake to Begnas. Less developed, perfect for kayaking and birdwatching.', 'https://images.unsplash.com/photo-1439066615861-d1e4672a254d?w=800&q=80', 4.4, 22, 600, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Begnas Hidden Shore', 'begnas-hidden-shore', 'Lake', 'Gandaki Province', 'Secluded western shore of Begnas Lake. Quiet boat rides and local fish restaurants.', 'https://images.unsplash.com/photo-1439066615861-d1e4672a254d?w=800&q=80', 4.5, 18, 650, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Bhujung Village', 'bhujung-village', 'Cultural', 'Gandaki Province', 'Traditional Gurung village with honey hunting traditions. Largest Gurung settlement.', 'https://images.unsplash.com/photo-1527684651878-5a8972479188?w=800&q=80', 4.6, 25, 1700, 'Moderate', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Ghandruk Upper Trail', 'ghandruk-upper-trail', 'Hiking', 'Gandaki Province', 'Alternative route avoiding main ABC crowds. Traditional Ghandruk village base.', 'https://images.unsplash.com/photo-1464822759023-fed622ff2cfa?w=800&q=80', 4.7, 34, 1950, 'Moderate', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Kori Danda', 'kori-danda', 'Trekking', 'Gandaki Province', 'Stunning viewpoint ridge above Sikles. Dramatic sunrise over Annapurna and Manaslu.', 'https://images.unsplash.com/photo-1501785888041-af3ef2d57d8a?w=800&q=80', 4.8, 21, 3550, 'Moderate', ARRAY['Oct', 'Nov'], true),
('Lwang Village', 'lwang-village', 'Cultural', 'Gandaki Province', 'Tea-growing village in Annapurna foothills. Tea tourism and village homestays.', 'https://images.unsplash.com/photo-1527684651878-5a8972479188?w=800&q=80', 4.5, 17, 1600, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Tara Hilltop', 'tara-hilltop', 'Hiking', 'Gandaki Province', '360-degree panorama of entire Annapurna range. Best sunset viewpoint in region.', 'https://images.unsplash.com/photo-1501785888041-af3ef2d57d8a?w=800&q=80', 4.6, 14, 2100, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Armala Caves', 'armala-caves', 'Adventure', 'Gandaki Province', 'Limestone caves near Pokhara with stalactites and underground streams. Adventure sport hub.', 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&q=80', 4.3, 11, 950, 'Moderate', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Bhirkot', 'bhirkot', 'Heritage', 'Gandaki Province', 'Old Newari town on trade route to Tibet. Traditional architecture and bazaar.', 'https://images.unsplash.com/photo-1544735716-392fe5a5c385?w=800&q=80', 4.2, 8, 1400, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Bhujung Forest', 'bhujung-forest', 'Wildlife', 'Gandaki Province', 'Community forest with bird watching towers. Home to 200+ species including laughing thrush.', 'https://images.unsplash.com/photo-1444021465936-c6ca81d6b3c8?w=800&q=80', 4.3, 7, 1700, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Mardi Ridge Trail', 'mardi-ridge-trail', 'Trekking', 'Gandaki Province', 'Underrated alternative to ABC. Spectacular campsites with fewer trekkers.', 'https://images.unsplash.com/photo-1464822759023-fed622ff2cfa?w=800&q=80', 4.7, 19, 3200, 'Moderate', ARRAY['Mar', 'Apr', 'Oct', 'Nov'], false),
('Nagi Village', 'nagi-village', 'Cultural', 'Gandaki Province', 'Eco-tourism model village with sustainable practices. Community-run homestays.', 'https://images.unsplash.com/photo-1527684651878-5a8972479188?w=800&q=80', 4.5, 15, 2300, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false);