/*
# Comprehensive Destination Data - Batch 2

Adding complete data for Province 3 (Bagmati) & Province 4 (Gandaki) destinations
*/

-- Province 3 (Bagmati) Destinations
UPDATE destinations SET 
  elevation_m = 2070,
  difficulty = 'Moderate',
  duration_days = '2 Days',
  transport = 'Drive from Kathmandu (1.5 hrs) to Sanga, then jeep to Nagidanda',
  budget_min = 4000,
  budget_max = 7000,
  network = 'NTC/Ncell Good',
  best_season = 'Year-round',
  safety_info = 'Easy trail near Kathmandu. Popular weekend hike.',
  sunrise_spot = 'Nagidanda View Tower',
  sunset_spot = 'Panauti Valley View',
  photography_tips = 'Great panoramic Himalaya views near Kathmandu.',
  nearest_hospital = 'Dhulikhel Hospital',
  nearest_hospital_km = 15,
  nearest_police = 'Sanga Police Post',
  nearest_police_km = 3,
  nearest_health_post = 'Nagidanda Health Post',
  nearest_health_post_km = 1,
  local_rescue = 'Local volunteers',
  local_foods = ARRAY['Dal Bhat', 'Chiya', 'Sel Roti'],
  cultural_tips = 'Newari culture predominant. Respect local traditions.',
  wildlife = ARRAY['Birds', 'Butterflies', 'Rhododendron'],
  festivals_nearby = 'Indra Jatra, Dashain',
  things_to_respect = 'No smoking in temples, dress modestly',
  score_adventure = 3,
  score_crowd = 3,
  score_cleanliness = 4,
  score_photography = 4,
  score_family = 4,
  score_budget = 5,
  score_safety = 5
WHERE name LIKE '%Nagidanda%';

UPDATE destinations SET 
  elevation_m = 2791,
  difficulty = 'Moderate',
  duration_days = '3-4 Days',
  transport = 'Drive from Kathmandu to Chautara, then trek',
  budget_min = 12000,
  budget_max = 18000,
  network = 'Limited',
  best_season = 'Mar-May, Oct-Nov',
  safety_info = 'Medium altitude trek. Tea houses available.',
  sunrise_spot = 'Panch Pokhari Summit',
  sunset_spot = 'Lake shore camp',
  photography_tips = 'Five sacred lakes with reflections.',
  nearest_hospital = 'Chautara Hospital',
  nearest_hospital_km = 35,
  nearest_police = 'Chautara Police',
  nearest_police_km = 30,
  nearest_health_post = 'Tripurasundari Health Post',
  nearest_health_post_km = 10,
  local_rescue = 'Local volunteers',
  local_foods = ARRAY['Dal Bhat', 'Dhido', 'Nettle soup'],
  cultural_tips = 'Sacred Hindu-Buddhist pilgrimage site.',
  wildlife = ARRAY['Musk Deer', 'Danfe', 'Rhododendron'],
  festivals_nearby = 'Janai Purnima',
  things_to_respect = 'No fishing in sacred lakes, maintain silence',
  score_adventure = 4,
  score_crowd = 4,
  score_cleanliness = 4,
  score_photography = 5,
  score_family = 2,
  score_budget = 3,
  score_safety = 4
WHERE name LIKE '%Panch Pokhari%';

UPDATE destinations SET 
  elevation_m = 2310,
  difficulty = 'Easy',
  duration_days = '1 Day',
  transport = 'Drive from Kathmandu (4 hrs)',
  budget_min = 3000,
  budget_max = 5000,
  network = 'Good',
  best_season = 'Year-round',
  safety_info = 'Popular viewpoint, easy drive.',
  sunrise_spot = 'View Tower',
  sunset_spot = 'Daman Ridge',
  photography_tips = 'Best panoramic Himalaya view on highway.',
  nearest_hospital = 'Hetauda Hospital',
  nearest_hospital_km = 40,
  nearest_police = 'Daman Police',
  nearest_police_km = 2,
  nearest_health_post = 'Daman Health Post',
  nearest_health_post_km = 1,
  local_rescue = 'Local volunteers',
  local_foods = ARRAY['Dal Bhat', 'Local Thali', 'Chiya'],
  cultural_tips = 'Highway stop with famous viewpoints.',
  wildlife = ARRAY['Birds', 'Hill flora'],
  festivals_nearby = 'Dashain',
  things_to_respect = 'Drive carefully on highway',
  score_adventure = 2,
  score_crowd = 3,
  score_cleanliness = 4,
  score_photography = 5,
  score_family = 5,
  score_budget = 5,
  score_safety = 5
WHERE name LIKE '%Daman%';

UPDATE destinations SET 
  elevation_m = 1528,
  difficulty = 'Moderate',
  duration_days = '1-2 Days',
  transport = 'Drive from Kathmandu (3 hrs)',
  budget_min = 5000,
  budget_max = 9000,
  network = 'Good',
  best_season = 'Year-round',
  safety_info = 'Popular biking/cycling destination.',
  sunrise_spot = 'Lakhuri Hilltop',
  sunset_spot = 'Panauti Valley View',
  photography_tips = 'Himalaya views and traditional village.',
  nearest_hospital = 'Dhulikhel Hospital',
  nearest_hospital_km = 20,
  nearest_police = 'Lakhuri Police',
  nearest_police_km = 5,
  nearest_health_post = 'Lamidanda Health Post',
  nearest_health_post_km = 3,
  local_rescue = 'Local volunteers',
  local_foods = ARRAY['Newari Thali', 'Yomari', 'Chatamari'],
  cultural_tips = 'Newari heritage village experiences.',
  wildlife = ARRAY['Birds', 'Terraced farms'],
  festivals_nearby = 'Indra Jatra',
  things_to_respect = 'Respect Newari traditions, ask before photographing',
  score_adventure = 3,
  score_crowd = 3,
  score_cleanliness = 4,
  score_photography = 4,
  score_family = 5,
  score_budget = 4,
  score_safety = 5
WHERE name LIKE '%Lakuri%' OR name LIKE '%Lakhuri%';

-- Province 4 (Gandaki) Destinations
UPDATE destinations SET 
  elevation_m = 1600,
  difficulty = 'Moderate',
  duration_days = '2 Days',
  transport = 'Drive from Pokhara (2 hrs) to Bijayapur',
  budget_min = 3500,
  budget_max = 6000,
  network = 'NTC Good',
  best_season = 'Mar-May, Oct-Nov',
  safety_info = 'Well-marked trail through Gurung villages.',
  sunrise_spot = 'Korchan Hilltop',
  sunset_spot = 'Pothana Village',
  photography_tips = 'Stunning valley and mountain views.',
  nearest_hospital = 'Pokhara Hospital',
  nearest_hospital_km = 18,
  nearest_police = 'Bijayapur Police',
  nearest_police_km = 5,
  nearest_health_post = 'Pothana Health Post',
  nearest_health_post_km = 3,
  local_rescue = 'Local Gurung guides',
  local_foods = ARRAY['Gurung Thali', 'Momo', 'Thukpa'],
  cultural_tips = 'Traditional Gurung hospitality.',
  wildlife = ARRAY['Monkeys', 'Birds', 'Rhododendron'],
  festivals_nearby = 'Tamu Lhosar',
  things_to_respect = 'Support homestays, ask before photographing',
  score_adventure = 3,
  score_crowd = 4,
  score_cleanliness = 4,
  score_photography = 5,
  score_family = 4,
  score_budget = 4,
  score_safety = 5
WHERE name LIKE '%Pothana%' OR name LIKE '%Australian Camp%';

UPDATE destinations SET 
  elevation_m = 1450,
  difficulty = 'Easy',
  duration_days = '1-2 Days',
  transport = 'Jeep from Pokhara (3 hrs) or trek from Kande',
  budget_min = 4000,
  budget_max = 7000,
  network = 'NTC/Ncell Good',
  best_season = 'Year-round',
  safety_info = 'Easy community trek.',
  sunrise_spot = 'Korchan Top',
  sunset_spot = 'Danda View',
  photography_tips = 'Rhododendron forests and Gurung culture.',
  nearest_hospital = 'Pokhara Hospital',
  nearest_hospital_km = 15,
  nearest_police = 'Kande Police',
  nearest_police_km = 5,
  nearest_health_post = 'Lwang Health Post',
  nearest_health_post_km = 2,
  local_rescue = 'Community volunteers',
  local_foods = ARRAY['Gurung Thali', 'Sel Roti', 'Local tea'],
  cultural_tips = 'Community-run homestay experience.',
  wildlife = ARRAY['Butterflies', 'Birds', 'Orchids'],
  festivals_nearby = 'Tamu Lhosar',
  things_to_respect = 'Support community homestays, organic farming',
  score_adventure = 2,
  score_crowd = 5,
  score_cleanliness = 5,
  score_photography = 4,
  score_family = 5,
  score_budget = 4,
  score_safety = 5
WHERE name LIKE '%Lwang%' OR name LIKE '%Gurung Lodge%';

UPDATE destinations SET 
  elevation_m = 3000,
  difficulty = 'Challenging',
  duration_days = '4-5 Days',
  transport = 'Trek from Pokhara or Sikles',
  budget_min = 18000,
  budget_max = 28000,
  network = 'None',
  best_season = 'Apr-May, Oct-Nov',
  safety_info = 'Remote trail to sacred lake. Guide recommended.',
  sunrise_spot = 'Khayar Summit',
  sunset_spot = 'Lake camp',
  photography_tips = 'Sacred high altitude lake with reflections.',
  nearest_hospital = 'Pokhara Hospital',
  nearest_hospital_km = 80,
  nearest_police = 'Sikles Police',
  nearest_police_km = 40,
  nearest_health_post = 'Sikles Health Post',
  nearest_health_post_km = 25,
  local_rescue = 'Local rescue volunteers',
  local_foods = ARRAY['Dal Bhat', 'Tongba', 'Tsampa'],
  cultural_tips = 'Sacred Gurung pilgrimage site.',
  wildlife = ARRAY['Musk Deer', 'Blue Sheep', 'Snow Trout'],
  festivals_nearby = 'Janai Purnima',
  things_to_respect = 'No fishing, maintain purity of lake',
  score_adventure = 5,
  score_crowd = 5,
  score_cleanliness = 4,
  score_photography = 5,
  score_family = 1,
  score_budget = 2,
  score_safety = 3
WHERE name LIKE '%Khayar%';

UPDATE destinations SET 
  elevation_m = 4530,
  difficulty = 'Challenging',
  duration_days = '7-9 Days',
  transport = 'Trek from Besishahar via Manang',
  budget_min = 35000,
  budget_max = 55000,
  network = 'None',
  best_season = 'Oct-Nov, Mar-Apr',
  safety_info = 'High altitude crossing. Acclimatization essential.',
  sunrise_spot = 'Lake camp',
  sunset_spot = 'Larkya descent',
  photography_tips = 'Stunning ice lake and glacier views.',
  nearest_hospital = 'Manang Hospital',
  nearest_hospital_km = 50,
  nearest_police = 'Manang Police',
  nearest_police_km = 45,
  nearest_health_post = 'Manang Health Post',
  nearest_health_post_km = 40,
  local_rescue = 'HRA Rescue',
  local_foods = ARRAY['Dal Bhat', 'Tibetan bread', 'Thukpa'],
  cultural_tips = 'Strong Buddhist traditions.',
  wildlife = ARRAY['Blue Sheep', 'Snow Leopard (rare)', 'Yaks'],
  festivals_nearby = 'Losar',
  things_to_respect = 'Circumambulate clockwise, no leather in monasteries',
  score_adventure = 5,
  score_crowd = 4,
  score_cleanliness = 4,
  score_photography = 5,
  score_family = 1,
  score_budget = 1,
  score_safety = 2
WHERE name LIKE '%Ice Lake%' OR name LIKE '%Kicho%';

UPDATE destinations SET 
  elevation_m = 1980,
  difficulty = 'Easy',
  duration_days = '1-2 Days',
  transport = 'Jeep from Pokhara to Sikles',
  budget_min = 3500,
  budget_max = 6000,
  network = 'NTC Good',
  best_season = 'Year-round',
  safety_info = 'Easy village trek.',
  sunrise_spot = 'Sikles viewpoint',
  sunset_spot = 'Village terraces',
  photography_tips = 'Traditional Gurung village and mountain views.',
  nearest_hospital = 'Pokhara Hospital',
  nearest_hospital_km = 35,
  nearest_police = 'Sikles Police',
  nearest_police_km = 2,
  nearest_health_post = 'Sikles Health Post',
  nearest_health_post_km = 1,
  local_rescue = 'Local volunteers',
  local_foods = ARRAY['Gurung Thali', 'Momo', 'Sel Roti'],
  cultural_tips = 'Authentic Gurung village experience.',
  wildlife = ARRAY['Birds', 'Hill flora'],
  festivals_nearby = 'Tamu Lhosar',
  things_to_respect = 'Support local homestays',
  score_adventure = 2,
  score_crowd = 4,
  score_cleanliness = 4,
  score_photography = 4,
  score_family = 5,
  score_budget = 4,
  score_safety = 5
WHERE name LIKE '%Sikles%';