/*
# Province 7 and Hidden Gems Seed Data

Adding destinations for Sudurpashchim Province and 20 top hidden gems.
*/

-- ============================================
-- PROVINCE 7: SUDURPASHCHIM - 20 Places
-- ============================================
INSERT INTO destinations (name, slug, category, region, description, image_url, rating, review_count, altitude_m, difficulty, best_months, featured) VALUES
('Khaptad Hidden Trail', 'khaptad-hidden-trail', 'Hiking', 'Sudurpashchim Province', 'Less-visited trails in Khaptad National Park. Wild meadows and spiritual energy.', 'https://images.unsplash.com/photo-1452421827683-b3a5bdb7c813?w=800&q=80', 4.7, 18, 3050, 'Moderate', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], true),
('Badimalika', 'badimalika', 'Trekking', 'Sudurpashchim Province', 'Sacred temple trek through remote hills. Full moon festivals draw thousands.', 'https://images.unsplash.com/photo-1501785888041-af3ef2d57d8a?w=800&q=80', 4.8, 23, 4150, 'Hard', ARRAY['May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct'], true),
('Ramaroshan', 'ramaroshan', 'Lake', 'Sudurpashchim Province', 'Wetland with 12 interconnected lakes. Bird paradise in Achham district.', 'https://images.unsplash.com/photo-1439066615861-d1e4672a254d?w=800&q=80', 4.6, 14, 2300, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], true),
('Api Base Trail', 'api-base-trail', 'Trekking', 'Sudurpashchim Province', 'Remote trek to base camp of Api Himal (7132m). Untouched wilderness.', 'https://images.unsplash.com/photo-1464822759023-fed622ff2cfa?w=800&q=80', 4.9, 11, 4100, 'Hard', ARRAY['May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct'], true),
('Saipal View', 'saipal-view', 'Hiking', 'Sudurpashchim Province', 'Rare viewpoint of Saipal Himal. Clear views from Bajhang hills.', 'https://images.unsplash.com/photo-1501785888041-af3ef2d57d8a?w=800&q=80', 4.5, 6, 2800, 'Moderate', ARRAY['Oct', 'Nov'], false),
('Shuklaphanta Grassland', 'shuklaphanta-grassland', 'Wildlife', 'Sudurpashchim Province', 'Prime habitat for endangered swamp deer. Safari drives and elephant rides.', 'https://images.unsplash.com/photo-1506905925346-21bda18d6ff1?w=800&q=80', 4.6, 34, 180, 'Easy', ARRAY['Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar'], false),
('Jhilmil Tal', 'jhilmil-tal', 'Lake', 'Sudurpashchim Province', 'Wetland lake known for waterfowl. Part of Shuklaphanta buffer zone.', 'https://images.unsplash.com/photo-1439066615861-d1e4672a254d?w=800&q=80', 4.3, 8, 200, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', ' Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Tripura Sundari Temple', 'tripura-sundari-temple', 'Heritage', 'Sudurpashchim Province', 'Historic temple complex in Dadeldhura. Intricate wood carvings and old bazaar.', 'https://images.unsplash.com/photo-1544735716-392fe5a5c385?w=800&q=80', 4.4, 27, 1100, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Dadeldhura Hills', 'dadeldhura-hills', 'Hiking', 'Sudurpashchim Province', 'Pine-covered hills with hiking trails. Gateway to Far West region.', 'https://images.unsplash.com/photo-1448375240586-882707db8882?w=800&q=80', 4.2, 9, 1450, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Ugratara Area', 'ugratara-area', 'Cultural', 'Sudurpashchim Province', 'Temple complex dedicated to Goddess Tara. Ancient architecture and pilgrimages.', 'https://images.unsplash.com/photo-1527684651878-5a8972479188?w=800&q=80', 4.3, 15, 900, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Jogbudha Valley', 'jogbudha-valley', 'Nature', 'Sudurpashchim Province', 'Scenic river valley near Mahakali. Traditional villages and terraced farms.', 'https://images.unsplash.com/photo-1508854710579-5bbda85edf64?w=800&q=80', 4.1, 5, 600, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Chure Forest Far West', 'chure-forest-far-west', 'Wildlife', 'Sudurpashchim Province', 'Sal forest corridor in Chure range. Wildlife corridor connecting to India.', 'https://images.unsplash.com/photo-1448375240586-882707db8882?w=800&q=80', 4.0, 4, 350, 'Easy', ARRAY['Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar'], false),
('Khaptad Patan', 'khaptad-patan', 'Hiking', 'Sudurpashchim Province', 'High-altitude grasslands (patan) in Khaptad. Rolling meadows perfect for walking.', 'https://images.unsplash.com/photo-1452421827683-b3a5bdb7c813?w=800&q=80', 4.5, 12, 3100, 'Moderate', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Ganesh Himal West View', 'ganesh-himal-west-view', 'Hiking', 'Sudurpashchim Province', 'Hidden viewpoint with rare western perspective of Ganesh Himal.', 'https://images.unsplash.com/photo-1501785888041-af3ef2d57d8a?w=800&q=80', 4.2, 3, 2600, 'Moderate', ARRAY['Oct', 'Nov'], false),
('Bhajang Villages', 'bhajang-villages', 'Cultural', 'Sudurpashchim Province', 'Traditional Chhetri and Brahmin villages. Mountain culture and customs.', 'https://images.unsplash.com/photo-1527684651878-5a8972479188?w=800&q=80', 4.4, 7, 2000, 'Moderate', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Doti Palace Ruins', 'doti-palace-ruins', 'Heritage', 'Sudurpashchim Province', 'Ancient Doti kingdom palace ruins. Stone foundations and temple remnants.', 'https://images.unsplash.com/photo-1570179534610-9c1d8e3bdde7?w=800&q=80', 4.1, 5, 1200, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Chameliya Valley', 'chameliya-valley', 'Nature', 'Sudurpashchim Province', 'River valley through Darchula. Scenic drive with suspension bridges and terraces.', 'https://images.unsplash.com/photo-1529158867021-99f5fd9a9772?w=800&q=80', 4.3, 8, 1000, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Api Nampa Villages', 'api-nampa-villages', 'Cultural', 'Sudurpashchim Province', 'Remote mountain villages near Api Nampa Conservation Area. Authentic culture.', 'https://images.unsplash.com/photo-1527684651878-5a8972479188?w=800&q=80', 4.6, 6, 2500, 'Moderate', ARRAY['May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct'], false),
('Budar Forest', 'budar-forest', 'Hiking', 'Sudurpashchim Province', 'Peaceful forest hike near Doti. Pine and oak woods with birdlife.', 'https://images.unsplash.com/photo-1448375240586-882707db8882?w=800&q=80', 4.0, 3, 1600, 'Easy', ARRAY['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], false),
('Surma Sarovar', 'surma-sarovar', 'Lake', 'Sudurpashchim Province', 'Remote alpine lake near Tibet border. Sacred pilgrimage for locals.', 'https://images.unsplash.com/photo-1439066615861-d1e4672a254d?w=800&q=80', 4.7, 4, 3800, 'Hard', ARRAY['May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct'], true);

-- ============================================
-- HIDDEN GEMS - Top 20 Best Picks
-- ============================================
INSERT INTO hidden_gems (name, slug, region, description, image_url, nature_score, tags, pilot_pick, guide_favorite, peaceful) VALUES
('Khumai Danda', 'khumai-danda', 'Gandaki Province', 'The ultimate hidden viewpoint. See Annapurna South face like nowhere else. Community-run eco-trek with sustainable practices.', 'https://images.unsplash.com/photo-1501785888041-af3ef2d57d8a?w=800&q=80', 9.5, ARRAY['sunrise', 'community-trek'], true, false, false),
('Bheda Kharka', 'bheda-kharka', 'Bagmati Province', 'Alpine meadows where sheep graze in summer. Nagarkot''s secret viewpoint with no crowds.', 'https://images.unsplash.com/photo-1464822759023-fed622ff2cfa?w=800&q=80', 9.0, ARRAY['meadows', 'sunrise'], true, false, false),
('Silichong Peak', 'silichong-peak', 'Koshi Province', 'Challenging hidden peak with technical climbing. Views of Makalu that few ever see.', 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&q=80', 8.8, ARRAY['climbing', 'technical'], true, false, false),
('Milke Danda', 'milke-danda', 'Koshi Province', '25km ridge walk - Nepal''s most beautiful rhododendron journey. Kanchenjunga to Makalu panorama.', 'https://images.unsplash.com/photo-1452421827683-b3a5bdb7c813?w=800&q=80', 9.3, ARRAY['rhododendron', 'panorama'], false, true, false),
('Kapuche Lake', 'kapuche-lake', 'Gandaki Province', 'World''s lowest glacier lake at 2450m. Turquoise waters reflecting Annapurna - magical.', 'https://images.unsplash.com/photo-1439066615861-d1e4672a254d?w=800&q=80', 9.4, ARRAY['glacier-lake', 'photography'], true, false, false),
('Panch Pokhari', 'panch-pokhari', 'Bagmati Province', 'Five sacred lakes at 4100m. Wilderness pilgrimage far from trekking crowds.', 'https://images.unsplash.com/photo-1439066615861-d1e4672a254d?w=800&q=80', 9.2, ARRAY['sacred', 'high-altitude'], false, true, false),
('Murma Top', 'murma-top', 'Karnali Province', 'Best Rara Lake viewpoint. Easy climb for sunrise panorama over the queen of lakes.', 'https://images.unsplash.com/photo-1501785888041-af3ef2d57d8a?w=800&q=80', 9.1, ARRAY['lake-view', 'sunrise'], true, false, false),
('Mohare Danda', 'mohare-danda', 'Gandaki Province', 'Community eco-trek at its finest. Annapurna views without the crowds - sustainable tourism model.', 'https://images.unsplash.com/photo-1464822759023-fed622ff2cfa?w=800&q=80', 9.3, ARRAY['eco-trek', 'community'], false, true, false),
('Bethanchok', 'bethanchok', 'Bagmati Province', 'King of Hills. Full Himalayan sweep from Langtang to Everest - Kavre''s best kept secret.', 'https://images.unsplash.com/photo-1501785888041-af3ef2d57d8a?w=800&q=80', 8.9, ARRAY['panorama', 'less-crowded'], false, true, false),
('Rolpa Jaljala', 'rolpa-jaljala', 'Lumbini Province', 'Rhododendron forests in rebel heartlands. Post-conflict tourism success story.', 'https://images.unsplash.com/photo-1452421827683-b3a5bdb7c813?w=800&q=80', 8.7, ARRAY['rhododendron', 'community'], false, false, true),
('Ramaroshan', 'ramaroshan', 'Sudurpashchim Province', '12 interconnected lakes in Achham. Bird paradise - Far West''s best wetland.', 'https://images.unsplash.com/photo-1439066615861-d1e4672a254d?w=800&q=80', 8.8, ARRAY['bird-watching', 'wetlands', 'less-crowded'], false, false, true),
('Mai Pokhari', 'mai-pokhari', 'Koshi Province', 'Sacred Ilam wetland with rare orchids. Home to the endangered spiny babbler.', 'https://images.unsplash.com/photo-1439066615861-d1e4672a254d?w=800&q=80', 8.6, ARRAY['ramsar', 'orchids'], false, true, false),
('Chankheli Trek', 'chankheli-trek', 'Karnali Province', 'Wild mountains, few trekkers. Untouched Humla wilderness - for serious adventurers.', 'https://images.unsplash.com/photo-1464822759023-fed622ff2cfa?w=800&q=80', 9.0, ARRAY['remote', 'adventure'], true, false, false),
('Ghyampe Danda', 'ghyampe-danda', 'Bagmati Province', 'Chandragiri''s hidden sibling. Same views, zero tourists. Kathmandu''s secret escape.', 'https://images.unsplash.com/photo-1501785888041-af3ef2d57d8a?w=800&q=80', 8.5, ARRAY['less-crowded', 'day-hike'], true, false, false),
('Markhu', 'markhu', 'Bagmati Province', 'Kulekhani''s quiet shore. Boat rides and hill walks without the crowds.', 'https://images.unsplash.com/photo-1439066615861-d1e4672a254d?w=800&q=80', 8.3, ARRAY['lake', 'day-trip'], false, false, true),
('Lwang Village', 'lwang-village', 'Gandaki Province', 'Tea-growing Gurung village. Sustainable village tourism model near Pokhara.', 'https://images.unsplash.com/photo-1527684651878-5a8972479188?w=800&q=80', 8.6, ARRAY['tea-tourism', 'homestay'], false, true, false),
('Limi Valley', 'limi-valley', 'Karnali Province', 'Ancient salt trade route to Tibet. Trans-Himalayan culture unchanged for centuries.', 'https://images.unsplash.com/photo-1464822759023-fed622ff2cfa?w=800&q=80', 9.4, ARRAY['trans-himalayan', 'ancient'], true, false, false),
('Tinjure Hill', 'tinjure-hill', 'Koshi Province', 'Rhododendron capital - 30+ species in one place. Pink hills April-May.', 'https://images.unsplash.com/photo-1452421827683-b3a5bdb7c813?w=800&q=80', 8.9, ARRAY['rhododendron', 'spring'], false, true, false),
('Sabha Pokhari', 'sabha-pokhari', 'Koshi Province', 'Sacred Kirat lake at 4200m. Pristine wilderness in remote Taplejung.', 'https://images.unsplash.com/photo-1439066615861-d1e4672a254d?w=800&q=80', 9.1, ARRAY['sacred', 'high-altitude'], true, false, false),
('Api Base Trail', 'api-base-trail', 'Sudurpashchim Province', 'Remote Api Himal base camp. Far West wilderness - Nepal''s last frontier.', 'https://images.unsplash.com/photo-1464822759023-fed622ff2cfa?w=800&q=80', 9.2, ARRAY['remote', 'mountaineering'], true, false, false);