/*
# Comprehensive Destination Data - Batch 1

Adding complete data for all Province 1 & 2 destinations
*/

-- Province 1 (Koshi) Destinations
UPDATE destinations SET 
  elevation_m = 2200,
  difficulty = 'Moderate',
  duration_days = '3-4 Days',
  transport = 'Flight to Bajhang or drive from Dhangadi',
  budget_min = 18000,
  budget_max = 30000,
  network = 'Limited NTC',
  best_season = 'Oct-Nov, Mar-May',
  safety_info = 'Remote trail, guide recommended. Weather can change quickly.',
  sunrise_spot = 'Mundum Peak',
  sunset_spot = 'Silgadhi Viewpoint',
  photography_tips = 'Ancient Mundum trail with cultural heritage.',
  nearest_hospital = 'Chainpur Hospital',
  nearest_hospital_km = 45,
  nearest_police = 'Bajhang Police',
  nearest_police_km = 30,
  nearest_health_post = 'Local Health Post',
  nearest_health_post_km = 5,
  local_rescue = 'Local Volunteer Team',
  local_foods = ARRAY['Dal Bhat', 'Roti', 'Tongba'],
  cultural_tips = 'Respect Mundum religious sites.',
  wildlife = ARRAY['Wild Boar', 'Monal Pheasant', 'Rhododendron'],
  festivals_nearby = 'Ubhauli',
  things_to_respect = 'No shoes in sacred sites',
  score_adventure = 5,
  score_crowd = 5,
  score_cleanliness = 4,
  score_photography = 4,
  score_family = 2,
  score_budget = 3,
  score_safety = 3
WHERE name LIKE '%Mundum%';

UPDATE destinations SET 
  elevation_m = 1800,
  difficulty = 'Easy',
  duration_days = '1 Day',
  transport = 'Bus from Ilam',
  budget_min = 2000,
  budget_max = 4000,
  network = 'NTC Good',
  best_season = 'Year-round',
  safety_info = 'Easy day hike, suitable for families.',
  sunrise_spot = 'Lake viewpoint',
  sunset_spot = 'Garden area',
  photography_tips = 'Best for lake reflection shots in early morning.',
  nearest_hospital = 'Ilam Hospital',
  nearest_hospital_km = 15,
  nearest_police = 'Ilam Police',
  nearest_police_km = 15,
  nearest_health_post = 'Ilam Health Post',
  nearest_health_post_km = 10,
  local_rescue = 'Local volunteers',
  local_foods = ARRAY['Chiya', 'Sel Roti', 'Local pickle'],
  cultural_tips = 'Lake considered sacred, no swimming.',
  wildlife = ARRAY['Migratory birds', 'Lotus flowers'],
  festivals_nearby = 'Chath',
  things_to_respect = 'No fishing, maintain cleanliness',
  score_adventure = 2,
  score_crowd = 3,
  score_cleanliness = 5,
  score_photography = 5,
  score_family = 5,
  score_budget = 5,
  score_safety = 5
WHERE name LIKE '%Mai Pokhari%';

UPDATE destinations SET 
  elevation_m = 2800,
  difficulty = 'Challenging',
  duration_days = '4-5 Days',
  transport = 'Trek from Taplejung (flight to Suketar)',
  budget_min = 22000,
  budget_max = 35000,
  network = 'None',
  best_season = 'Oct-Nov, Mar-May',
  safety_info = 'High altitude, remote. Guide mandatory. Altitude sickness risk.',
  sunrise_spot = 'Tinjure Summit',
  sunset_spot = 'Rhododendron camp',
  photography_tips = 'Stunning rhododendron forests in bloom.',
  nearest_hospital = 'Taplejung Hospital',
  nearest_hospital_km = 60,
  nearest_police = 'Taplejung Police',
  nearest_police_km = 60,
  nearest_health_post = 'Timbu Health Post',
  nearest_health_post_km = 20,
  local_rescue = 'TAP Rescue',
  local_foods = ARRAY['Dal Bhat', 'Nettle soup', 'Tongba'],
  cultural_tips = 'Respect Limbu traditions.',
  wildlife = ARRAY['Red Panda', 'Musk Deer', 'Rhododendron', 'Migratory birds'],
  festivals_nearby = 'Chasok Tangnam',
  things_to_respect = 'No hunting, sacred groves',
  score_adventure = 5,
  score_crowd = 5,
  score_cleanliness = 5,
  score_photography = 5,
  score_family = 1,
  score_budget = 2,
  score_safety = 3
WHERE name LIKE '%Tinjure%';

UPDATE destinations SET 
  elevation_m = 3800,
  difficulty = 'Challenging',
  duration_days = '5-7 Days',
  transport = 'Trek from Taplejung or Basantpur',
  budget_min = 28000,
  budget_max = 45000,
  network = 'None',
  best_season = 'Oct-Nov, Apr-May',
  safety_info = 'High altitude, remote. No rescue services nearby. Guide essential.',
  sunrise_spot = 'Milke Danda Summit',
  sunset_spot = 'Rhododendron camps',
  photography_tips = 'Best rhododendron display in Nepal.',
  nearest_hospital = 'Dhankuta Hospital',
  nearest_hospital_km = 80,
  nearest_police = 'Basantpur Police',
  nearest_police_km = 50,
  nearest_health_post = 'Gupha Pokhari Health Post',
  nearest_health_post_km = 15,
  local_rescue = 'Local volunteers',
  local_foods = ARRAY['Dal Bhat', 'Dhido', 'Local herbs tea'],
  cultural_tips = 'Traditional Rai and Limbu villages.',
  wildlife = ARRAY['Red Panda', 'Musk Deer', 'Danfe', 'Rhododendron'],
  festivals_nearby = 'Udhauli',
  things_to_respect = 'Respect sacred lakes, no plastic',
  score_adventure = 5,
  score_crowd = 5,
  score_cleanliness = 4,
  score_photography = 5,
  score_family = 1,
  score_budget = 2,
  score_safety = 2
WHERE name LIKE '%Milke%';

UPDATE destinations SET 
  elevation_m = 3794,
  difficulty = 'Challenging',
  duration_days = '7-10 Days',
  transport = 'Trek from Taplejung (flight to Suketar)',
  budget_min = 40000,
  budget_max = 65000,
  network = 'None',
  best_season = 'Oct-Nov, Apr-May',
  safety_info = 'High altitude route. Medical emergency evacuation costly. Guide mandatory.',
  sunrise_spot = 'Pathibhara Peak',
  sunset_spot = 'Temple viewpoint',
  photography_tips = 'Sacred temple with panoramic Himalayas.',
  nearest_hospital = 'Taplejung Hospital',
  nearest_hospital_km = 40,
  nearest_police = 'Taplejung Police',
  nearest_police_km = 40,
  nearest_health_post = 'Phungling Health Post',
  nearest_health_post_km = 10,
  local_rescue = 'HRA Rescue Team',
  local_foods = ARRAY['Prasad', 'Dal Bhat', 'Local sweets'],
  cultural_tips = 'Most sacred temple in East Nepal. Pilgrimage site.',
  wildlife = ARRAY['Blue sheep', 'Snow leopard (rare)', 'Rhododendron'],
  festivals_nearby = 'Navratri',
  things_to_respect = 'Remove leather articles, no non-veg food near temple',
  score_adventure = 5,
  score_crowd = 3,
  score_cleanliness = 4,
  score_photography = 5,
  score_family = 2,
  score_budget = 2,
  score_safety = 3
WHERE name LIKE '%Pathibhara%';

-- Province 2 (Madhesh) Destinations
UPDATE destinations SET 
  elevation_m = 150,
  difficulty = 'Easy',
  duration_days = '1 Day',
  transport = 'Bus from Janakpur',
  budget_min = 1500,
  budget_max = 3000,
  network = 'Good 4G',
  best_season = 'Oct-Mar',
  safety_info = 'Easy visit, safe for families.',
  sunrise_spot = 'Forest edge',
  sunset_spot = 'Lake viewpoint',
  photography_tips = 'Best bird watching in early morning.',
  nearest_hospital = 'Janakpur Hospital',
  nearest_hospital_km = 15,
  nearest_police = 'Dhanusha Police',
  nearest_police_km = 10,
  nearest_health_post = 'Local Health Post',
  nearest_health_post_km = 3,
  local_rescue = 'Local volunteers',
  local_foods = ARRAY['Maithili Thali', 'Lassi', 'Thekuwa'],
  cultural_tips = 'Sacred forest from Ramayana era.',
  wildlife = ARRAY['Deer', 'Migratory birds', 'Turtles'],
  festivals_nearby = 'Ram Navami, Vivah Panchami',
  things_to_respect = 'No hunting, maintain forest sanctity',
  score_adventure = 2,
  score_crowd = 2,
  score_cleanliness = 4,
  score_photography = 4,
  score_family = 5,
  score_budget = 5,
  score_safety = 5
WHERE name LIKE '%Dhanushadham%';

UPDATE destinations SET 
  elevation_m = 100,
  difficulty = 'Easy',
  duration_days = '2-3 Hours',
  transport = 'Bus from Janakpur',
  budget_min = 1000,
  budget_max = 2000,
  network = 'Good',
  best_season = 'Year-round',
  safety_info = 'Easy heritage visit.',
  sunrise_spot = 'Temple courtyard',
  sunset_spot = 'Market area',
  photography_tips = 'Magnificent Mithila architecture.',
  nearest_hospital = 'Janakpur Hospital',
  nearest_hospital_km = 8,
  nearest_police = 'Janakpur Police',
  nearest_police_km = 3,
  nearest_health_post = 'Janakpur Health Post',
  nearest_health_post_km = 2,
  local_rescue = 'Local volunteers',
  local_foods = ARRAY['Maithili Thali', 'Peda', 'Lassi'],
  cultural_tips = 'Birthplace of Goddess Sita. Major pilgrimage.',
  wildlife = ARRAY['N/A'],
  festivals_nearby = 'Ram Navami, Vivah Panchami',
  things_to_respect = 'Remove shoes in temple, dress modestly',
  score_adventure = 1,
  score_crowd = 2,
  score_cleanliness = 4,
  score_photography = 5,
  score_family = 5,
  score_budget = 5,
  score_safety = 5
WHERE name LIKE '%Janakpur%';

UPDATE destinations SET 
  elevation_m = 120,
  difficulty = 'Easy',
  duration_days = '1 Day',
  transport = 'Bus from Biratnagar',
  budget_min = 1200,
  budget_max = 2500,
  network = 'Good',
  best_season = 'Nov-Feb',
  safety_info = 'Easy wildlife safari.',
  sunrise_spot = 'Watch tower',
  sunset_spot = 'River bank',
  photography_tips = 'Best for bird and gharial photography.',
  nearest_hospital = 'Biratnagar Hospital',
  nearest_hospital_km = 25,
  nearest_police = 'Koshi Tappu Police',
  nearest_police_km = 5,
  nearest_health_post = 'Reserve Health Post',
  nearest_health_post_km = 3,
  local_rescue = 'Reserve Rangers',
  local_foods = ARRAY['Fish curry', 'Dal Bhat', 'Local sweets'],
  cultural_tips = 'Important wetland reserve.',
  wildlife = ARRAY['Wild Water Buffalo', 'Gharial', 'Dolphins', 'Migratory birds'],
  festivals_nearby = 'Chath',
  things_to_respect = 'No loud noises, no plastic in reserve',
  score_adventure = 3,
  score_crowd = 3,
  score_cleanliness = 4,
  score_photography = 5,
  score_family = 4,
  score_budget = 5,
  score_safety = 5
WHERE name LIKE '%Koshi%' OR name LIKE '%Tappu%';

-- Set default data for all other destinations
UPDATE destinations SET 
  network = COALESCE(network, CASE 
    WHEN difficulty = 'Challenging' THEN 'None/Limited'
    WHEN difficulty = 'Moderate' THEN 'NTC (limited)'
    ELSE 'Good 4G'
  END),
  best_season = COALESCE(best_season, 'Oct-Nov, Mar-May'),
  safety_info = COALESCE(safety_info, 
    CASE 
      WHEN difficulty = 'Challenging' THEN 'Remote area. Guide recommended. Carry essentials.'
      WHEN difficulty = 'Moderate' THEN 'Moderate difficulty. Stay on marked trails.'
      ELSE 'Easy access, suitable for families.'
    END
  ),
  score_adventure = COALESCE(score_adventure, CASE WHEN difficulty = 'Challenging' THEN 5 WHEN difficulty = 'Moderate' THEN 4 ELSE 3 END),
  score_crowd = COALESCE(score_crowd, 4),
  score_cleanliness = COALESCE(score_cleanliness, 4),
  score_photography = COALESCE(score_photography, 4),
  score_family = COALESCE(score_family, CASE WHEN difficulty = 'Challenging' THEN 1 WHEN difficulty = 'Moderate' THEN 3 ELSE 5 END),
  score_budget = COALESCE(score_budget, CASE WHEN difficulty = 'Challenging' THEN 2 WHEN difficulty = 'Moderate' THEN 3 ELSE 5 END),
  score_safety = COALESCE(score_safety, CASE WHEN difficulty = 'Challenging' THEN 2 WHEN difficulty = 'Moderate' THEN 4 ELSE 5 END),
  nearest_hospital = COALESCE(nearest_hospital, 'District Hospital'),
  nearest_hospital_km = COALESCE(nearest_hospital_km, CASE WHEN difficulty = 'Challenging' THEN 60 WHEN difficulty = 'Moderate' THEN 30 ELSE 15 END),
  nearest_police = COALESCE(nearest_police, 'Local Police Post'),
  nearest_police_km = COALESCE(nearest_police_km, CASE WHEN difficulty = 'Challenging' THEN 40 WHEN difficulty = 'Moderate' THEN 20 ELSE 5 END),
  nearest_health_post = COALESCE(nearest_health_post, 'Local Health Post'),
  nearest_health_post_km = COALESCE(nearest_health_post_km, CASE WHEN difficulty = 'Challenging' THEN 20 WHEN difficulty = 'Moderate' THEN 10 ELSE 3 END)
WHERE score_adventure IS NULL OR network IS NULL;